version: "3.8"
name: railroad-station-project

services:
  postgres:
    container_name: postgres_db
    image: postgres:14.7
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: railroad_station_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5437:5432"
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
  oracle-db:
    container_name: oracle_db
    image: container-registry.oracle.com/database/enterprise:latest
    environment:
      ORACLE_SID: railStateDb
      ORACLE_PDB: railStateDb1
      ORACLE_PWD: Oracle_123
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/railStateDb as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
  oracle-data:
  oracle-backup: